kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: google-sheets-secret-template
  namespace: demo-camelk
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      labels:
        app: ${RESOURCE_NAME}
      name: ${RESOURCE_NAME}
    stringData:
      camel.kamelet.google-sheets-source.clientId: ${SOURCE_CLIENT_ID}
      camel.kamelet.google-sheets-source.clientSecret: ${SOURCE_CLIENT_SECRET}
parameters:
  - name: RESOURCE_NAME
    displayName: Resource Name
    description: The name of the service resource that also matches POD app label.
    required: true
  - name: SOURCE_CLIENT_ID
    displayName: Source clientId
    description: The Google clientId to use for the connection to Google Sheets.
    required: true
  - name: SOURCE_CLIENT_SECRET
    displayName: Source clientSecret
    description: The Google clientSecret to use for the connection to Google Sheets.
    required: true
