apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: stage1
  namespace: demo-camelk
spec:
  integration:
    configuration:
     - type: "secret"
       value: "stage1"


  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: google-sheets-source
    properties:
      applicationName: "your-application-name"
      accessToken:     "your-access-token"
      refreshToken:    "your-refresh-token"
      spreadsheetId:   "your-spreadsheet-id"
      index: "sheet1"
      range: "B5:D7"
      delay: 5000
      repeatCount: 1


  sink:
    ref:
      apiVersion: kafka.strimzi.io/v1beta1
      kind: KafkaTopic
      name: questions
