apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: stage1
  namespace: demo-camelk
spec:
  integration:
    configuration:
     - type: "secret"
       value: "stage1"


  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: google-sheets-source
    properties:
      applicationName: "democlient1"
      accessToken:   "ya29.a0AWY7CknMsq_UQAHphwSLlGICc1WHi4uUKzswS5ARNYdZ0QwONrB_r2Aub-PBjUC_o9eF3duPALrDS7zl-FvWBjXA9HMpQ6-yDPhmTKS1Zc7o9s9NO6PZoto3Yx2-9XBdY8q9Zw-1Mr1QpoykzfjEqBxlF6BfaCgYKAckSARESFQG1tDrpPfffoy4A91RC156wTHBfUA0163"
      refreshToken:  "1//04WoSOKCMQoNsCgYIARAAGAQSNwF-L9IrT9tEpFYHhqJeYvFrqG4VU4UKcgMFt2vjZ26ZiQZAc9BYhKlWrGZ0o_l6erHOjFNZ3-E"
      spreadsheetId: "13uKVKWP8YbJVOf0Df5uQQnSyhwxl3vCY5kDg-PxUuOc"
      index: "Sheet1"
      range: "B5:D7"
      delay: 5000
      repeatCount: 1


  sink:
    ref:
      apiVersion: kafka.strimzi.io/v1beta1
      kind: KafkaTopic
      name: questions