apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/catalog.version: 4.0.0-SNAPSHOT
    camel.apache.org/kamelet.group: Google Sheets
    camel.apache.org/kamelet.icon: >-
      data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI1LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA2NCA4OCIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgNjQgODg7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCS5zdDB7ZmlsbDojMERDNTRDO30KCS5zdDF7ZmlsbDojMDg5NjJEO30KCS5zdDJ7ZmlsbDojRkRGRkZGO30KPC9zdHlsZT4KPGcgaWQ9IkxheWVyXzQiPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTU4LDg4SDZjLTMuMywwLTYtMi43LTYtNlY2YzAtMy4zLDIuNy02LDYtNmgzNmwyMiwyMnY2MEM2NCw4NS4zLDYxLjMsODgsNTgsODh6Ii8+Cgk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNNDIsMGwyMiwyMkg0MlYweiIvPgoJPHBhdGggY2xhc3M9InN0MiIgZD0iTTEyLDM0LjV2MjhoNDB2LTI4SDEyeiBNMTcsMzkuNWgxMi41VjQ2SDE3VjM5LjV6IE0xNyw1MWgxMi41djYuNUgxN1Y1MXogTTQ3LDU3LjVIMzQuNVY1MUg0N1Y1Ny41eiBNNDcsNDYKCQlIMzQuNXYtNi41SDQ3VjQ2eiIvPgo8L2c+Cjwvc3ZnPgo=
    camel.apache.org/kamelet.namespace: GCP
    camel.apache.org/kamelet.support.level: Stable
    camel.apache.org/provider: Apache Software Foundation
  name: google-sheets-source
  labels:
    camel.apache.org/kamelet.type: source
spec:
  definition:
    description: Receive data from Google Sheets.
    properties:
      delay:
        default: 500
        description: The number of milliseconds before the next poll
        title: Delay
        type: integer
      clientId:
        description: Client ID of the sheets application
        format: password
        title: Client Id
        type: string
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:password'
          - 'urn:camel:group:credentials'
      spreadsheetId:
        description: The Spreadsheet ID to be used as events source
        title: Spreadsheet ID
        type: string
      repeatCount:
        description: Specifies a maximum limit of number of fires
        title: Repeat Count
        type: integer
      accessToken:
        description: >-
          OAuth 2 access token for google sheets application. This typically
          expires after an hour so refreshToken is recommended for long term
          usage.
        format: password
        title: Access Token
        type: string
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:password'
          - 'urn:camel:group:credentials'
      clientSecret:
        description: Client Secret of the sheets application
        format: password
        title: Client Secret
        type: string
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:password'
          - 'urn:camel:group:credentials'
      applicationName:
        description: Google Sheets application name
        title: Application name
        type: string
      splitResults:
        default: true
        description: >-
          True if value range result should be split into rows or columns to
          process each of them individually.
        title: Split Results
        type: boolean
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:checkbox'
      range:
        description: the range of rows and columns in a sheet to get data from.
        example: 'A1:B3'
        title: Cells Range to get Data from
        type: string
      refreshToken:
        description: >-
          OAuth 2 refresh token for google sheets application. Using this, the
          Google Calendar component can obtain a new accessToken whenever the
          current one expires - a necessity if the application is long-lived.
        format: password
        title: Refresh Token
        type: string
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:password'
          - 'urn:camel:group:credentials'
    required:
      - spreadsheetId
      - clientId
      - accessToken
      - refreshToken
      - clientSecret
    title: Google Sheets Source
    type: object
  dependencies:
    - 'camel:jackson'
    - 'camel:kamelet'
    - 'camel:google-sheets'
  template:
    from:
      parameters:
        delay: '{{delay}}'
        clientId: '{{clientId}}'
        repeatCount: '{{?repeatCount}}'
        accessToken: '{{accessToken}}'
        clientSecret: '{{clientSecret}}'
        applicationName: '{{?applicationName}}'
        splitResults: '{{splitResults}}'
        range: '{{?range}}'
        refreshToken: '{{refreshToken}}'
      steps:
        - marshal:
            json: {}
        - to: 'kamelet:sink'
      uri: 'google-sheets-stream://{{spreadsheetId}}'
  types:
    out:
      mediaType: application/json

